apiVersion: v1
kind: Pod
metadata:
  name: test-container
spec:
  containers:
      - name: mymicroservice
        image: acrvmlyrswgc.azurecr.io/mymicroservice:v2
        ports:
        - containerPort: 3000